local Core = MidnightSensei.Core

Core.RegisterSpec(7, {
    className = "Shaman",

    -- Elemental (Midnight 12.0 pass — April 2026; spell snapshot + verify audit April 2026; May 2026 Archon sweep)
    -- Chain Lightning (188443) added to rotational — previously tracked, lost to compaction; id=188443 confirmed; primary AoE filler
    -- Removed:  Primordial Wave (375982) — pruned in Midnight 12.0; functionality merged into
    --           Voltaic Blaze which handles AoE Flame Shock automatically
    -- Removed:  Fire Elemental (198067) — no longer a manual summon in Midnight 12.0;
    --           auto-generated by Ascendance as part of Stormbringer design
    -- Removed:  60103 from rotationalSpells — this is Lava Lash (Enhancement), not Lava Burst
    -- Removed:  Earth Shock (8042) — not tracked; situational Maelstrom spender, not universally applicable
    -- Removed:  Flame Shock (470411) — not available to Elemental in Midnight 12.0; Enhancement only
    --           Voltaic Blaze (470057) is the Elemental Shaman's Flame Shock replacement
    -- Added:    Earthquake (462620) as talentGated rotational — confirmed Elemental Talent nodeID 80985
    -- Added:    Elemental Blast (117014) as talentGated rotational — confirmed Elemental Talent nodeID 80984
    -- Added:    Voltaic Blaze (470057) as talentGated rotational — nodeID 81007; Flame Shock replacement for Elemental
    -- Added:    Lightning Bolt (188196) as baseline rotational — confirmed spell list; primary filler
    -- Added:    Earth Elemental (198103) to majorCooldowns — live-verified id=198103 fired=1x; baseline defensive CD
    -- Added:    Ancestral Swiftness (443454) to majorCooldowns — Farseer hero talent; talentGated; ~30s CD window
    -- Added:    Spiritwalker's Grace (79206) to majorCooldowns as isUtility — nodeID 103584; 2 min CD; 100% adoption
    -- Added:    Wind Rush Totem (192077) to majorCooldowns as isUtility — nodeID 103627; talentGated; 94% adoption
    -- Tempest (454009) — confirmed PASSIVE nodeID 94892; not tracked
    -- Tempest (452201) — DIFFERENT ID; this is the Stormkeeper-empowered Lightning Bolt/Chain Lightning cast
    --   event in Midnight 12.0. Fires UNIT_SPELLCAST_SUCCEEDED. Tracked via altIds={452201} on Lightning Bolt.
    -- Lightning Capacitor, Inferno Arc, Primal Elementalist — confirmed PASSIVE; not tracked
    -- Not added: Lava Surge (77756) to procBuffs — confirmed in Elemental Spell List as player aura
    --            but needs in-game C_UnitAuras.GetPlayerAuraBySpellID verification before adding
    -- Confirmed: Lava Burst cast ID = 51505 (UNIT_SPELLCAST_SUCCEEDED verified in-game, fired 7x)
    -- Confirmed: Ascendance (114050) live-verified fired=1x — fires UNIT_SPELLCAST_SUCCEEDED on both Farseer and Stormbringer
    [1] = {
        name = "Elemental", role = "DPS",
        resourceType = 11, resourceLabel = "MAELSTROM", overcapAt = 90,
        majorCooldowns = {
            { id = 191634, label = "Stormkeeper",        expectedUses = "on CD"                              },  -- confirmed nodeID 80988
            { id = 114050, label = "Ascendance",         expectedUses = "burst windows"                      },  -- live-verified fired=1x; fires SUCCEEDED on both hero paths
            { id = 198103, label = "Earth Elemental",    expectedUses = "defensive / tank threat"            },  -- live-verified id=198103 fired=1x; baseline CD
            { id = 443454, label = "Ancestral Swiftness",  expectedUses = "on CD (~30s)",    talentGated = true, minFightSeconds = 30 },  -- Farseer hero talent; live-verified fired=1x
            { id = 79206,  label = "Spiritwalker's Grace", expectedUses = "movement phases",  isUtility = true, talentGated = true },       -- nodeID 103584; 2 min CD; 100% adoption; tracked, never penalised
            { id = 192077, label = "Wind Rush Totem",      expectedUses = "movement phases",  isUtility = true, talentGated = true },       -- nodeID 103627; 94% adoption; tracked, never penalised
        },
        -- uptimeBuffs intentionally empty: Flame Shock is a target debuff,
        -- not detectable via C_UnitAuras.GetPlayerAuraBySpellID.
        uptimeBuffs = {},
        rotationalSpells = {
            { id = 188196, label = "Lightning Bolt",  minFightSeconds = 15, altIds = {452201} },        -- confirmed spell list; primary filler; 452201 = Stormkeeper-empowered cast (Tempest morph)
            { id = 51505,  label = "Lava Burst",      minFightSeconds = 15 },                          -- non-PASSIVE ACTIVE nodeID 103598; cast ID confirmed in-game
            { id = 462620, label = "Earthquake",      minFightSeconds = 30, talentGated = true, altIds = {61882, 61982} },  -- altIds: classic cast IDs per Archon (May 2026); both added per mismatch policy
            { id = 117014, label = "Elemental Blast", minFightSeconds = 20, talentGated = true },      -- non-PASSIVE ACTIVE nodeID 80984
            { id = 188443, label = "Chain Lightning",  minFightSeconds = 15 },                          -- primary AoE filler; empowered by Stormkeeper; id=188443 confirmed; previously tracked, re-added May 2026
            { id = 470057, label = "Voltaic Blaze",   minFightSeconds = 20, talentGated = true },      -- nodeID 81007; Flame Shock replacement for Elemental — DoT applicator
            { id = 8042,   label = "Earth Shock",    minFightSeconds = 15, hasCombatValue = true, isUtility = true, suppressIfTalent = 117014 },  -- Maelstrom spender; suppressed when Elemental Blast (117014) is talented
            -- Flame Shock (470411) removed — Enhancement only in Midnight 12.0; Voltaic Blaze replaces it for Elemental
            -- Tempest (454009) removed — confirmed PASSIVE nodeID 94892
        },
        priorityNotes = {
            "Voltaic Blaze is the Flame Shock replacement for Elemental — maintain the DoT when talented",
            "Lava Burst on cooldown — always consume Lava Surge procs immediately",
            "Chain Lightning as primary AoE filler — empowered by Stormkeeper on multi-target pulls",
            "Lightning Bolt as primary ST filler — empowered by Stormkeeper for single-target burst",
            "Stormkeeper before empowered Lightning Bolt or Chain Lightning casts for maximum burst",
            "Elemental Blast to spend Maelstrom (single target, when talented) — avoid overcap at 90",
            "Earthquake to spend Maelstrom on AoE — avoid overcap at 90",
            "Ascendance for burst — automatically summons Fire Elemental in Midnight 12.0",
            "Earth Elemental on cooldown — baseline defensive CD, use for tank threat or personal mitigation",
            "Ancestral Swiftness on cooldown when talented (Farseer) — ~30s window, use proactively",
        },
        scoreWeights = { cooldownUsage = 35, activity = 40, resourceMgmt = 25 },
        sourceNote = "Midnight 12.0 verified against spell snapshot + talent tree 112 nodes (April 2026); May 2026 Archon sweep",
    },

    -- Enhancement (Midnight 12.0 PASSIVE audit — April 2026)
    -- Feral Spirit: was 51533 — talent tree confirms 469314 PASSIVE. Removed entirely.
    -- Ascendance: was 114051 — not in Enhancement talent tree at all. Removed.
    -- Primordial Wave (375982): not in Enhancement talent tree or spell list. Removed.
    -- Maelstrom Weapon procBuff: was 344179 — spell list confirms 187880. Corrected.
    -- Surging Totem (444995) added to majorCooldowns — non-PASSIVE ACTIVE nodeID 94877
    -- Crash Lightning (187874) added to rotational — non-PASSIVE ACTIVE nodeID 80974
    -- Lava Lash (60103) added to rotational — non-PASSIVE ACTIVE nodeID 109389
    -- Voltaic Blaze (470057) added as talentGated rotational — non-PASSIVE ACTIVE nodeID 80954
    -- Stormstrike (32175) added to rotational — primary builder; was missing from rotationalSpells
    --   altId 17364 also fires UNIT_SPELLCAST_SUCCEEDED; 32176 is Off-Hand proc (not a cast event)
    -- Fire Nova (1260666) confirmed PASSIVE nodeID 109909 — not tracked
    [2] = {
        name = "Enhancement", role = "DPS",
        resourceType = 11, resourceLabel = "MAELSTROM", overcapAt = 140,
        majorCooldowns = {
            { id = 384352, label = "Doom Winds",    expectedUses = "burst windows",  talentGated = true, suppressIfTalent = 114051 },  -- non-PASSIVE ACTIVE nodeID 80959; suppressed when Ascendance (114051) is talented (choice node; Ascendance replaces Doom Winds on action bar)
            { id = 114051, label = "Ascendance",    expectedUses = "on CD",          talentGated = true },  -- confirmed in tree (choice node with Doom Winds); nodeID 92219; 2 min CD; fires UNIT_SPELLCAST_SUCCEEDED (07/11/2026 in-game verified)
            { id = 197214, label = "Sundering",     expectedUses = "on CD (talent)", talentGated = true },  -- non-PASSIVE ACTIVE nodeID 80975
            { id = 444995, label = "Surging Totem", expectedUses = "on CD (talent)", talentGated = true },  -- non-PASSIVE ACTIVE nodeID 94877
            -- Feral Spirit (51533/469314) removed — PASSIVE
            -- Primordial Wave (375982) removed — not in Midnight 12.0
        },
        uptimeBuffs = {},
        procBuffs = {
            { id = 187880, label = "Maelstrom Weapon", maxStackTime = 20 },  -- confirmed spell list (was 344179)
        },
        rotationalSpells = {
            { id = 32175,  label = "Stormstrike",    minFightSeconds = 15, altIds = {17364} },    -- primary builder; 32176 is Off-Hand proc (not cast event)
            { id = 187874, label = "Crash Lightning", minFightSeconds = 15 },                     -- non-PASSIVE ACTIVE nodeID 80974
            { id = 60103,  label = "Lava Lash",       minFightSeconds = 15 },                     -- non-PASSIVE ACTIVE nodeID 109389
            { id = 470057, label = "Voltaic Blaze",   minFightSeconds = 20, talentGated = true }, -- non-PASSIVE ACTIVE nodeID 80954
            { id = 188443, label = "Chain Lightning", minFightSeconds = 20, talentGated = true }, -- AoE optional; same ID as Elemental; talentGated given ~7.5% adoption (May 2026)
        },
        priorityNotes = {
            "Maintain Flame Shock on targets for Hot Hand procs and Lava Lash damage (not directly tracked)",
            "Spend Maelstrom Weapon at 5+ stacks — spend at 10 before any cap",
            "Stormstrike on cooldown — primary builder and damage source",
            "Lava Lash to spread Flame Shock in multi-target and spend Maelstrom stacks",
            "Crash Lightning before AoE pulls to apply the ground effect",
            "Doom Winds at peak Maelstrom / burst window when talented",
            "Surging Totem on cooldown when talented — significant throughput increase",
            "Avoid Maelstrom Weapon overcap — spend with Lightning Bolt or Elemental Blast",
        },
        scoreWeights = { cooldownUsage = 30, procUsage = 30, activity = 25, resourceMgmt = 15 },
        sourceNote = "Midnight 12.0 PASSIVE audit against full Enhancement talent tree 102 nodes (April 2026)",
    },

    -- Restoration (Midnight 12.0 pass — April 2026)
    -- Lava Burst (51505) added to rotationalSpells as isUtility — cast ID confirmed (same as Elemental);
    --   optional filler DPS for Resto; bonus credit if used, never penalised for omission
    -- Stormstream Totem (1267016) confirmed PASSIVE nodeID 110403 — not tracked (May 2026 audit)
    -- Removed:  Cloudburst Totem (157153) — pruned from Restoration in Midnight 12.0
    --           as part of spec simplification removing high-timing-skill buttons
    -- Removed:  Ancestral Guidance (108281) — removed from game in Midnight (patch 11.1.0 / Feb 25 2025)
    -- Healing Tide Totem (108280) — re-added to majorCooldowns (May 2026); in-game tooltip confirmed active, talentGated, healerConditional (3 min CD)
    --   prior removal note was incorrect; tooltip confirmed active via in-game test
    -- Also pruned by Blizzard (not tracked): Earthen Wall Totem, Ancestral Protection Totem,
    --           Wellspring, High Tide, Tidebringer, Undulation, Master of the Elements,
    --           Mana Tide, Tide Turner, Spiritwalker's Tidal Totem
    -- Added:    Surging Totem (444995) — Totem hero talent (talentGated); confirmed Resto Talent nodeID 94877
    --           replaces Cloudburst Totem as the signature throughput cooldown
    -- Added:    Unleash Life (73685) to majorCooldowns — confirmed Resto Talent nodeID 92677
    --           pre-heal amplifier, strong on-cooldown usage; not healerConditional (use every CD)
    -- Added:    Call of the Ancestors (443450) as talentGated cooldown — confirmed nodeID 94888
    -- Added:    rotationalSpells: Riptide, Chain Heal, Healing Rain — all confirmed in Resto files
    -- Added:    Healing Wave (77472) to rotationalSpells — confirmed id=77472 fired=6x; baseline filler
    -- Added:    Healing Stream Totem (5394) to rotationalSpells — confirmed id=5394 fired=3x; ~30s CD
    -- Kept:     Spirit Link Totem (98008) confirmed nodeID 81041; healerConditional (fight-dependent)
    --           Ascendance (114052) confirmed nodeID 81032; healerConditional (emergency use)
    --           Surging Totem (444995) healerConditional (may not be needed every fight)
    --           Healing Rain (73920) moved to rotationalSpells (maintained on CD, not a burst CD)
    -- Added:    Nature's Swiftness (378081) to majorCooldowns — nodeID 103620; 1 min CD; talentGated; suppressIfTalent=443454
    --           (Ancestral Swiftness replaces it when Farseer hero talent is taken)
    -- Added:    Ancestral Swiftness (443454) to majorCooldowns — Farseer hero talent; nodeID 94894; talentGated
    --           replaces Nature's Swiftness (378081) when taken
    [3] = {
        name = "Restoration", role = "HEALER",
        resourceType = 0,
        majorCooldowns = {
            { id = 57994,  label = "Wind Shear",         expectedUses = "on interrupt",                 isInterrupt = true       },  -- confirmed id=57994 fired=1x
            { id = 77130,  label = "Purify Spirit",      expectedUses = "on magic/curse debuffs",       isUtility = true         },  -- confirmed id=77130 fired=1x; cleanse, no penalty
            { id = 98008,  label = "Spirit Link Totem", expectedUses = "dangerous health disparities", healerConditional = true },  -- non-PASSIVE ACTIVE nodeID 81041
            { id = 444995, label = "Surging Totem",     expectedUses = "before damage windows",        healerConditional = true, talentGated = true },  -- non-PASSIVE ACTIVE nodeID 94877; Totem hero talent
            { id = 73685,  label = "Unleash Life",      expectedUses = "on CD — pre-heal amplifier"                             },  -- non-PASSIVE ACTIVE nodeID 92675
            { id = 114052, label = "Ascendance",        expectedUses = "emergency throughput",         healerConditional = true },  -- non-PASSIVE ACTIVE nodeID 81032
            { id = 108280, label = "Healing Tide Totem",    expectedUses = "healing CD (talent)",  healerConditional = true, talentGated = true },  -- confirmed active Midnight 12.0; re-added May 2026; 3 min CD
            { id = 378081, label = "Nature's Swiftness",   expectedUses = "on CD (talent)",        talentGated = true, suppressIfTalent = 443454 },  -- nodeID 103620; 1 min CD; suppressed when Farseer hero talent (Ancestral Swiftness 443454) is taken
            { id = 443454, label = "Ancestral Swiftness",  expectedUses = "on CD (~30s)",          talentGated = true },  -- Farseer hero talent; nodeID 94894; replaces Nature's Swiftness (378081)
            { id = 462486, label = "Downpour",           expectedUses = "on CD (talent)",              talentGated = true, isUtility = true },  -- AoE spot healing; tracked, never penalised
            -- Call of the Ancestors (443450) removed — confirmed PASSIVE nodeID 94888
            -- Earth Shield (974) intentionally not tracked — nodeID 103596; cast pre-pull creates false negatives;
            --   Midnight changes make mid-fight reapplication timing inconsistent; no penalty warranted
        },
        uptimeBuffs = {},
        rotationalSpells = {
            { id = 51505,  label = "Lava Burst",            minFightSeconds = 20, isUtility = true },  -- optional filler DPS; bonus credit if used, never penalised
            { id = 61295,  label = "Riptide",               minFightSeconds = 15 },  -- confirmed nodeID 81027; core maintenance HoT
            { id = 77472,  label = "Healing Wave",          minFightSeconds = 15 },  -- confirmed id=77472 fired=6x; baseline filler heal
            { id = 1064,   label = "Chain Heal",            minFightSeconds = 20 },  -- confirmed in Resto files; primary group heal
            { id = 73920,  label = "Healing Rain",          minFightSeconds = 30, altIds = {456366} },  -- confirmed nodeID 81040; 456366 fires when Surging Totem hero talent augments the cast
            { id = 5394,   label = "Healing Stream Totem",  minFightSeconds = 30 },  -- confirmed id=5394 fired=3x; use on cooldown (~30s)
        },
        healerMetrics = { targetOverheal = 30, targetActivity = 80, targetManaEnd = 15 },
        priorityNotes = {
            "Keep Riptide rolling on 2-3 injured targets at all times — primary HoT maintenance",
            "Healing Wave as primary filler — efficient single-target baseline heal",
            "Healing Stream Totem on cooldown (~30s) — passive trickle heal while casting",
            "Unleash Life on cooldown — pre-heal amplifier, use before Chain Heal or Healing Rain",
            "Healing Rain on stacked groups — keep it active, high mana efficiency",
            "Chain Heal for group damage when multiple targets are injured",
            "Surging Totem before predictable raid damage windows when talented (Totem hero path)",
            "Spirit Link Totem to equalize dangerous health imbalances across the raid",
            "Ascendance for emergency throughput — not a maintenance cooldown",
            "Avoid excessive overheal — cast slightly later on targets above 70% health",
        },
        scoreWeights = { cooldownUsage = 25, efficiency = 30, activity = 25, responsiveness = 20 },
        sourceNote = "Midnight 12.0 PASSIVE audit against full Restoration talent tree 110 nodes (April 2026); May 2026 second-pass",
    },
})
